astra-token: AstraCS:FldtuLSNmOcnevIIUzXwcyEb:9e45296b143b7d106b35440f08e4731b4914dcfba315a314a93131c873286757
astra-database-id: dec5b8e7-f2ed-4142-849f-e068580b07ea
astra-timeout: 30s
bind: 127.0.0.1:9042
rpc-address: 127.0.0.1
data-center: us-east4
track-usage: true
usage-keyspace: qt
# USAGE TRACKING DEFAULTS
# usage-table: astra_usage_stats
# usage-track-system: false
# usage-rru-bytes: 4096
# usage-wru-bytes: 1024
# usage-flush-seconds: 60
# usage-histograms-table: astra_usage_histograms
# peers:
#   - rpc-address: 127.0.0.1
#     data-center: us-east4
#   - rpc-address: 127.0.0.2
#     data-center: dc-2
# ...
